### ISSUE TITLE
Remove some authors from paper

### ISSUE THREAD

**Issue by mbolboceanu** [CodeByAidan/Homomorphic-Encryption-Decryption-with-Strings#3]
Hey,

I took a look at the paper (the pdf) you wrote with the explanations on the HE scheme. Could you please remove our names as authors on the paper? I think it is a bit misleading, as we didn't contribute to it, we only have a piece of code. :) I consider it suffices just to give credit to me and my colleagues at the end of the paper, as you wrote already. Thank you! :)

**Comment by CodeByAidan** [comment]
Sorry will do!
